app.controller('snackableController',
	['$scope', function($scope){

		$scope.allStarDist = [
			{
				rank: 34,
				percentile: 74,
				name: "Dru Charlesburg",
				gameNum: 55,
				gameDays: "7",
				district: "1f",
				member: "Cinder",
				deathDay: "7",
				placement: "2",
				tScore: 10,
				kills: 2,
				zscore: 5.57
			},
			{
				rank: 20,
				percentile: 80,
				name: "Reyes Moreno",
				gameNum: 60,
				gameDays: "8",
				district: "1m",
				member: "Thundy",
				deathDay: "8",
				placement: "2",
				tScore: 10,
				kills: 3,
				zscore: 6.402
			},
			{
				rank: 25,
				percentile: 78,
				name: "Circe Lyon",
				gameNum: 70,
				gameDays: "8",
				district: "2f",
				member: "Kay",
				deathDay: "6",
				placement: "5",
				tScore: 10,
				kills: 4,
				zscore: 6.059
			},
			{
				rank: 84,
				percentile: 61,
				name: "Orion Hammerfell",
				gameNum: 70,
				gameDays: "8",
				district: "2m",
				member: "Cato",
				deathDay: "7",
				placement: "4",
				tScore: 9,
				kills: 1,
				zscore: 3.68
			},
			{
				rank: 35,
				percentile: 74,
				name: "Kiena Ward",
				gameNum: 70,
				gameDays: "8",
				district: "3f",
				member: "Stare",
				deathDay: "7",
				placement: "3",
				tScore: 9,
				kills: 3,
				zscore: 5.489
			},
			{
				rank: 16,
				percentile: 82,
				name: "Sawyer Monaghan",
				gameNum: 59,
				gameDays: "7",
				district: "3m",
				member: "Charade",
				deathDay: "7",
				placement: "3",
				tScore: 11,
				kills: 3,
				zscore: 6.655
			},
			{
				rank: 3,
				percentile: 91,
				name: "River Destin",
				gameNum: 63,
				gameDays: "8",
				district: "4f",
				member: "South",
				deathDay: "8",
				placement: "2",
				tScore: 10,
				kills: 5,
				zscore: 8.066
			},
			{
				rank: 50,
				percentile: 69,
				name: "Fitz Ripley",
				gameNum: 61,
				gameDays: "8",
				district: "4m",
				member: "Windy",
				deathDay: "8",
				placement: "2",
				tScore: 4,
				kills: 4,
				zscore: 4.849
			},
			{
				rank: 22,
				percentile: 80,
				name: "Laila Sycamore",
				gameNum: 66,
				gameDays: "9",
				district: "5f",
				member: "Python",
				deathDay: "9",
				placement: "2",
				tScore: 10,
				kills: 3,
				zscore: 6.402
			},
			{
				rank: 95,
				percentile: 59,
				name: "Storm Wie",
				gameNum: 57,
				gameDays: "8",
				district: "5m",
				member: "Dee",
				deathDay: "6",
				placement: "4",
				tScore: 7,
				kills: 2,
				zscore: 3.346
			},
			{
				rank: 14,
				percentile: 82,
				name: "Gypsy Keeni",
				gameNum: 63,
				gameDays: "8",
				district: "6f",
				member: "Lulu",
				deathDay: "8",
				placement: "3",
				tScore: 9,
				kills: 4,
				zscore: 6.692
			},
			{
				rank: 15,
				percentile: 82,
				name: "Ansel Khiev",
				gameNum: 77,
				gameDays: "8",
				district: "6m",
				member: "Kousei",
				deathDay: "7",
				placement: "4",
				tScore: 9,
				kills: 6,
				zscore: 6.678
			},
			{
				rank: 21,
				percentile: 80,
				name: "Yaa Valarro",
				gameNum: 64,
				gameDays: "8",
				district: "7f",
				member: "Thundy",
				deathDay: "8",
				placement: "2",
				tScore: 10,
				kills: 3,
				zscore: 6.402
			},
			{
				rank: 36,
				percentile: 73,
				name: "Alexander Hood",
				gameNum: 59,
				gameDays: "7",
				district: "7m",
				member: "Aya",
				deathDay: "6",
				placement: "6",
				tScore: 10,
				kills: 3,
				zscore: 5.401
			},
			{
				rank: 28,
				percentile: 76,
				name: "Aria Wolfe",
				gameNum: 62,
				gameDays: "9",
				district: "8F",
				member: "Zoe",
				deathDay: "9",
				placement: "3",
				tScore: 9,
				kills: 3,
				zscore: 5.86
			},
			{
				rank: 19,
				percentile: 80,
				name: "Jared Strahan",
				gameNum: 54,
				gameDays: "9",
				district: "8m",
				member: "Lulu",
				deathDay: "9",
				placement: "2",
				tScore: 10,
				kills: 3,
				zscore: 6.402
			},
			{
				rank: 129,
				percentile: 53,
				name: "Ivy Soren",
				gameNum: 63,
				gameDays: "8",
				district: "9f",
				member: "Clover",
				deathDay: "6",
				placement: "10",
				tScore: 9,
				kills: 1,
				zscore: 2.443
			},
			{
				rank: 11,
				percentile: 86,
				name: "Wednesdae Drummond",
				gameNum: 62,
				gameDays: "9",
				district: "9M",
				member: "Rook",
				deathDay: "9",
				placement: "2",
				tScore: 8,
				kills: 5,
				zscore: 7.271
			},
			{
				rank: 59,
				percentile: 68,
				name: "Riven Fowley",
				gameNum: 75,
				gameDays: "9",
				district: "10f",
				member: "Solo",
				deathDay: "7",
				placement: "14",
				tScore: 9,
				kills: 3,
				zscore: 4.623
			},
			{
				rank: 169,
				percentile: 48,
				name: "Rodrick Benstaloe",
				gameNum: 71,
				gameDays: "9",
				district: "10m",
				member: "Mattio",
				deathDay: "5",
				placement: "17",
				tScore: 9,
				kills: 2,
				zscore: 1.688
			},
			{
				rank: 57,
				percentile: 68,
				name: "Salome Izar",
				gameNum: 75,
				gameDays: "9",
				district: "11f",
				member: "Zori",
				deathDay: "8",
				placement: "6",
				tScore: 11,
				kills: 1,
				zscore: 4.661
			},
			{
				rank: 17,
				percentile: 81,
				name: "Iago Izar-McClaine",
				gameNum: 65,
				gameDays: "8",
				district: "11m",
				member: "Zori",
				deathDay: "7",
				placement: "4",
				tScore: 10,
				kills: 4,
				zscore: 6.574
			},
			{
				rank: 23,
				percentile: 78,
				name: "Charas Harp",
				gameNum: 59,
				gameDays: "7",
				district: "12f",
				member: "Cameron",
				deathDay: "5",
				placement: "9",
				tScore: 12,
				kills: 4,
				zscore: 6.171
			},
			{
				rank: 75,
				percentile: 65,
				name: "Asunder Hayes",
				gameNum: 63,
				gameDays: "8",
				district: "12m",
				member: "Kay",
				deathDay: "6",
				placement: "7",
				tScore: 6,
				kills: 4,
				zscore: 4.18
			}
		];

		

	}]);
